# ===================================
# Build Settings
# ===================================

markdown: kramdown

permalink: pretty


# ===================================
# Server (local only)
# ===================================

port: 4000


# ===================================
# Includes / Excludes
# ===================================

include:
  - _includes/work

exclude:
  - the_design.psd
  - README.md
  - node_modules
  - .DS_Store


# ===================================
# SASS / CSS
# ===================================

sass:
  sass_dir: assets/css
  style: compressed
  
