#-------------------------------

# General Site Settings

title: Academia
description: description
email: addyouremail

menu:

- {name: 'Project', url: 'https://besener.github.io/searlefellowsprogram/'}
- {name: 'Blog', url: 'https://besener.github.io/parchment/'}
- {name: 'About', url: 'https://www.besener.com/'}
- {name: 'Contact', url: 'https://arthistory.northwestern.edu/people/faculty/bihter-esener.html'}

#-------------------------------

# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Personal page powered by Jekyll and GitHub Pages '
  rel-author: 'https://plus.google.com/u/0/115391695226276326378'
  rel-publisher: 'https://plus.google.com/u/0/115391695226276326378'

#-------------------------------

# Google Analytics Section

# Analytics helps you understand who visits your website.

# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

#google-analytics-ua: UA-XXXXXX-X

#-------------------------------

# Project Section

project: >


#-------------------------------

# Blog Section

blog: >


#-------------------------------

# About Section

about: >

  # Lorem ipsum dolor sit amet, consectetur adipiscing elit. 


#-------------------------------
    
# Contact Section

contact: >

  # Lorem ipsum dolor sit amet, consectetur adipiscing elit.


#-------------------------------

# Work Section


#-------------------------------

footer: 

social:

- {icon: 'university', link: 'https://northwestern.academia.edu/BihterEsener'}
- {icon: 'github', link: 'https://www.github.com/besener'}
- {icon: 'linkedin', link: 'http://www.linkedin.com/in/besener'}
- {icon: 'instagram', link: 'https://www.instagram.com/bihter.esener'}
- {icon: 'flickr', link: 'https://www.flickr.com/photos/besener'}
- {icon: 'envelope', link: 'mailto:besener@northwestern.edu'}

# social network icons available courtesy of http://fontawesome.io/icons/
