#-------------------------------

# General Site Settings

title: your title
description: description
email: addyouremail

menu:

- {name: 'Blog', url: 'blog.html'}
- {name: 'About', url: 'about.html'}
- {name: 'Contact', url: 'contact.html'}

#-------------------------------

# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Personal page powered by Jekyll and GitHub Pages '
  rel-author: 'https://plus.google.com/u/0/115391695226276326378'
  rel-publisher: 'https://plus.google.com/u/0/115391695226276326378'

#-------------------------------

# Google Analytics Section

# Analytics helps you understand who visits your website.

# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

#google-analytics-ua: UA-XXXXXX-X

#-------------------------------

# About Section

about: >

  # Hello! Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur mollis tempor neque. Maecenas feugiat mauris id ex ultrices, at laoreet eros fringilla.

    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur mollis tempor neque. Maecenas feugiat mauris id ex ultrices, at laoreet eros fringilla. Quisque malesuada lacinia rhoncus. In consectetur, erat et aliquet sagittis, magna ex consequat risus, laoreet commodo eros dolor sed ante. Ut vel odio massa. Proin vitae felis et massa dictum egestas sit amet nec nisl. Nulla ut imperdiet nibh. Suspendisse et consectetur tellus. Nulla id purus condimentum nibh laoreet varius. Nunc lectus tellus, malesuada eu erat non, pharetra sagittis nulla. Cras commodo egestas odio, quis aliquam odio congue vitae.

    

contact: >

  # Contact

  You may contact me [through my email](mailto:addyouremail).

#-------------------------------

# Work Section


#-------------------------------

# Contact Section

footer: Elsewhere

social:

- {icon: 'university', link: 'http://academia.edu/'}
- {icon: 'instagram', link: 'https://www.instagram.com'}
- {icon: 'flickr', link: 'https://www.flickr.com'}
- {icon: 'bluesky', link: 'https://bluesky.app'}
- {icon: 'github', link: 'https://www.github.com/'}
- {icon: 'linkedin', link: 'http://www.linkedin.com/'}
- {icon: 'envelope', link: 'mailto:addyouremail'}

# social network icons available courtesy of http://fontawesome.io/icons/
