#-------------------------------

# General Site Settings

title: your title
description: art historian
email: addyouremail

menu:

- {name: 'Projects', url: 'projects.html'}
- {name: 'Blog', url: 'blog.html'}
- {name: 'About', url: 'about.html'}
- {name: 'Contact', url: 'contact.html'}

#-------------------------------

# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Personal page powered by Jekyll and GitHub Pages '
  rel-author: 'https://plus.google.com/u/0/115391695226276326378'
  rel-publisher: 'https://plus.google.com/u/0/115391695226276326378'

#-------------------------------

# Google Analytics Section

# Analytics helps you understand who visits your website.

# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

#google-analytics-ua: UA-XXXXXX-X

#-------------------------------

# About Section

about: >

  # Hello! Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur mollis tempor neque. Maecenas feugiat mauris id ex ultrices, at laoreet eros fringilla.

    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur mollis tempor neque. Maecenas feugiat mauris id ex ultrices, at laoreet eros fringilla. Quisque malesuada lacinia rhoncus. In consectetur, erat et aliquet sagittis, magna ex consequat risus, laoreet commodo eros dolor sed ante. Ut vel odio massa. Proin vitae felis et massa dictum egestas sit amet nec nisl. Nulla ut imperdiet nibh. Suspendisse et consectetur tellus. Nulla id purus condimentum nibh laoreet varius. Nunc lectus tellus, malesuada eu erat non, pharetra sagittis nulla. Cras commodo egestas odio, quis aliquam odio congue vitae.
    
    Ut euismod dui ipsum, nec interdum ex tristique ut. Duis porta, mi id placerat fermentum, est libero elementum justo, non rhoncus magna enim id orci. Donec dignissim, mi quis sagittis scelerisque, elit purus blandit magna, quis euismod diam metus vel sem. Cras fermentum tincidunt suscipit. Mauris congue pellentesque lorem ut auctor. Vivamus lacinia suscipit pharetra. In dignissim justo nisi, in tincidunt enim vulputate et. Integer id turpis ultrices, consectetur ligula consectetur, accumsan lacus. Vivamus lobortis ligula nec lobortis aliquam. Aliquam in laoreet neque. Duis ultrices sollicitudin nulla, ut pharetra orci dapibus a. Ut lacinia vel quam non pretium.
    
    Pellentesque dictum, elit ac dignissim tempor, tortor elit scelerisque magna, at sodales ante erat consectetur leo. Suspendisse vitae accumsan tortor. Integer lectus ligula, laoreet eget lacinia eu, efficitur eget turpis. Curabitur at finibus justo. Vestibulum euismod velit et mi iaculis, in finibus lacus interdum. Aliquam fringilla mauris velit, sit amet eleifend leo molestie et. Donec ac sagittis ex, eget auctor odio. In ut ornare libero. Vivamus nec tellus quis est luctus efficitur at nec sem. In bibendum a erat vel dignissim.I hold a Ph.D. in History of Art from Koç University, Istanbul. I am currently a College Fellow in the Department of Art History at Northwestern University, and will join the department as an Assistant Professor of medieval Mediterranean and Islamic art in the fall of 2025.
    
    I am one of the founding members of Khamseen: Islamic Art History Online, for which I serve as the Director of Digital Technologies, and an assistant editor at the International Journal of Islamic Architecture (IJIA). Before joining Northwestern, I was a Lecturer of medieval Mediterranean and Islamic art in the Department of the History of Art at the University of Michigan, where I also was an affiliated faculty at the Digital Studies Institute (DSI). I was previously a Research Assistant in the Digital Islamic Studies Curriculum (DISC) and a Freer Visiting Graduate Student Fellow in the History of Art at the University of Michigan as well as a Visiting Doctoral Student in History of Art at Bryn Mawr College.
    
    My research has been supported by various grants and institutions, including the American Research Institute in Turkey (ARIT)’s Hanfmann Fellowship, SOAS-Getty Connecting Art Histories Research Project, Koç University’s Stavros Niarchos Foundation Center for Late Antique and Byzantine Studies (GABAM), and The Digital Islamic Studies Curriculum (DISC) at the University of Michigan via a grant from the Andrew W. Mellon Foundation. My dissertation, which I am currently transforming into a book, contextualized bronze mirrors within the lives of the inhabitants of medieval Anatolia by considering their various functions in personal adornment and their use in devotional, divinatory, and talismanic practices during the Seljuk period, i.e., between the late eleventh and early fourteenth centuries. My research interests also include the collection and display of Islamic art in the nineteenth and twentieth centuries, the history of sports, environmental studies, digital art history, visualization, and game studies.

contact: >

  # Contact

  You may contact me [through my email](mailto:addyouremail) or [Bluesky](https://bsky.app/).

#-------------------------------

# Work Section

projects:

- {name: 'Project A', folder: 'proj-1', file: 'projects/projecta.html'}
- {name: 'Project B', folder: 'proj-2', file: 'projects/projectb.html'}
- {name: 'Project C', folder: 'proj-3', file: 'projects/projectc.html'}
- {name: 'Project D', folder: 'proj-4', file: 'projects/project-project-d.html'}

#-------------------------------

# Contact Section

footer: Follow me below

social:

- {icon: 'Bluesky', link: 'https://bluesky.app'}
- {icon: 'codepen', link: 'http://codepen.io/'}
- {icon: 'github', link: 'https://www.github.com/besener'}
- {icon: 'linkedin', link: 'http://www.linkedin.com/in/besener'}
- {icon: 'envelope', link: 'mailto:addyouremail'}

# social network icons available courtesy of http://fontawesome.io/icons/
